
[[redirects]]
  from = "/package"
  to = "/package@3.0.0/test.html"
  status = 302
  force = true

[[redirects]]
  from = "/package/*"
  to = "/package@3.0.0/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/package@3/*"
  to = "/package@3.0.0/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/package@3.0/*"
  to = "/package@3.0.0/:splat"
  status = 302
  force = true

[[redirects]]
  from = "/package@*"
  to = "/dist/package/:splat"
  status = 200
  force = true


[[headers]]
  for = "/*"
  [headers.values]
    access-control-allow-origin = "*"

[[headers]]
  for = "/package@*"
  [headers.values]
    cache-control = '''
    public,
    max-age=31536000'''
